export const jobs = [
  {
    id: '1',
    title: 'Frontend Developer',
    company: 'Kinetic Studio',
    location: 'Bandung, ID',
    type: 'Full-time',
    salary: 'Rp8.000.000 - Rp12.000.000',
    tags: ['Vue', 'Nuxt', 'TypeScript'],
  },
  {
    id: '2',
    title: 'UI/UX Designer',
    company: 'Pixel Craft',
    location: 'Jakarta, ID',
    type: 'Hybrid',
    salary: 'Rp7.000.000 - Rp10.000.000',
    tags: ['Figma', 'Design System', 'Prototype'],
  },
  {
    id: '3',
    title: 'Backend Engineer',
    company: 'Node Labs',
    location: 'Remote',
    type: 'Remote',
    salary: 'Rp10.000.000 - Rp15.000.000',
    tags: ['Node.js', 'API', 'PostgreSQL'],
  },
  {
    id: '4',
    title: 'Product Manager',
    company: 'Growth Works',
    location: 'Jakarta, ID',
    type: 'Full-time',
    salary: 'Rp12.000.000 - Rp18.000.000',
    tags: ['Strategy', 'Analytics', 'Roadmap'],
  },
  {
    id: '5',
    title: 'QA Engineer',
    company: 'Quality First',
    location: 'Bandung, ID',
    type: 'On-site',
    salary: 'Rp6.000.000 - Rp9.000.000',
    tags: ['Testing', 'Cypress', 'Automation'],
  },
  {
    id: '6',
    title: 'Data Analyst',
    company: 'Insight Hub',
    location: 'Remote',
    type: 'Contract',
    salary: 'Rp7.500.000 - Rp11.000.000',
    tags: ['SQL', 'Dashboard', 'BI'],
  },
]